app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('login');
});

Route::get('/orden/load', 'OrdenController@load')->name('orden.load');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => '/cliente'], function() {
        Route::get('/', 'ClienteController@index')->name('cliente.index');
        Route::get('/load', 'ClienteController@load')->name('cliente.load');
        Route::get('/crear', 'ClienteController@create')->name('cliente.crear');
        Route::post('/crear', 'ClienteController@store')->name('cliente.store');
        Route::get('/{cliente}', 'ClienteController@view')->name('cliente.view');
        Route::get('/{cliente}/edit', 'ClienteController@edit')->name('cliente.edit');
        Route::post('/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    });

    Route::group(['prefix' => '/json'], function() {
        Route::get('/cliente/buscar/{dni}', 'ClienteController@buscar')->name('cliente.buscar');
        Route::get('/tipo/{tipo}/marcas', 'TipoController@getMarcas')->name('marcas.tipo');
        Route::get('/tipo/{tipo}/marca/{marca}/modelos', 'TipoController@getModelos')->name('tipos.marcas.modelos');
    });

    Route::resource('tipos', 'TipoController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('modelos', 'ModeloController');
    Route::resource('prestadores', 'PrestadorController');

    Route::resource('fotos', 'FotoController');

    Route::get('/estados/{estado}/arriba', 'EstadoController@up')->name('estado.up');
    Route::get('/estados/{estado}/abajo', 'EstadoController@down')->name('estado.down');

    Route::resource('estados', 'EstadoController');

    Route::group(['prefix' => '/orden'], function() {
        Route::get('/', 'OrdenController@index')->name('orden.index');
        //Route::get('/load', 'OrdenController@load')->name('orden.load');
        Route::get('/{orden}', 'OrdenController@show')->name('orden.show');
        Route::get('/crear/cliente/{cliente}', 'OrdenController@create')->name('orden.create');
        Route::post('/crear', 'OrdenController@store')->name('orden.store');
        Route::post('/{orden}/precio', 'OrdenController@precio')->name('orden.precio');
        Route::post('/{orden}/estado', 'OrdenController@estadoUpdate')->name('orden.estadoupdate');
        Route::get('/{orden}/print', 'OrdenController@print')->name('orden.print');
        Route::get('/{orden}/edit', 'OrdenController@edit')->name('orden.edit');
        Route::post('/{orden}/update', 'OrdenController@update')->name('orden.update');

    });

    Route::group(['prefix' => '/usuarios'], function() {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('/crear', 'UserController@create')->name('users.create');
        Route::post('/', 'UserController@store')->name('users.store');
        Route::get('/{user}', 'UserController@show')->name('users.show');
        Route::get('/{user}/editar', 'UserController@edit')->name('users.edit');
        Route::post('/{user}', 'UserController@update')->name('users.update');
        Route::delete('/{user}', 'UserController@destroy')->name('users.destroy');
    });

    Route::get('/acceso/{user}/cambiar', 'UserController@editPassword')->name('users.password.edit');
    Route::post('/acceso/{user}', 'UserController@updatePassword')->name('users.password.update');

    Route::group(['prefix' => '/historial'], function() {
        Route::get('/{orden}/load', 'HistoriaController@load')->name('historia.load');
    });




//    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/app/Estado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estado extends Model
{
	protected $fillable = [
        'nombre', 'orden'
    ];

    public function getNextOrden()
    {
    	return $this->max('orden') + 1;
    }
}

app/app/Http/Controllers/EstadoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Estado;

class EstadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('estado.index', ['estados' => Estado::all()->sortBy('orden')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('estado.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $orden = Estado::max('orden') + 1;
        $estado = Estado::create(['nombre' => $request->input('nombre'), 'orden' => $orden]);

        return redirect(route('estados.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Estado '.$estado->nombre.' creada exitosamente.'
        ]);
    }

    public function up(Estado $estado)
    {
        Estado::where('orden',$estado->orden - 1)->update(['orden' => $estado->orden]);
        $estado->update(['orden' => $estado->orden-1]);

        return redirect(route('estados.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Cambio de orden de '.$estado->nombre.' exitosamente.'
        ]);
    }

    public function down(Estado $estado)
    {
        Estado::where('orden',$estado->orden + 1)->update(['orden' => $estado->orden]);
        $estado->update(['orden' => $estado->orden+1]);

        return redirect(route('estados.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Cambio de orden de '.$estado->nombre.' exitosamente.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/resources/views/estado/create.blade.php
@extends('layout', [
  'title' => 'Estado',
  'content_title' => 'Estado',
  'content_sub_title' => 'Nuevo'
])

@section('content')

<div class="row">
  <div class="col-md-8">
    <div class="box box-primary">
        <form class="form-horizontal" action="{{ route('estados.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="box-header">Estado Nuevo</div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" name="nombre" id="nombre" class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Crear</button>
            </div>
        </form>
    </div>
  </div>
</div>
@endsection

app/resources/views/estado/index.blade.php
@extends('layout', [
  'title' => 'Estados',
  'content_title' => 'Estados',
  'content_sub_title' => 'Listado'
])

@section('content')

  <div class="row">
    <div class="col-xs-2 col-xs-offset-10">
      <a class="btn btn-block btn-primary" href="{{ route('estados.create') }}">Crear Nuevo</a>
    </div>
  </div>
  <br>

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <table id="clientes" class="table table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Orden</th>
              <th colspan="2">Acciones</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($estados as $estado)
                <tr>
                    <td>{{ $estado->id }}</td>
                    <td>{{ $estado->nombre }}</td>
                    <td>{{ $estado->orden }}</td>
                    <td>
                        @if (!$loop->first)
                            <a href="{{route('estado.up',['estado' => $estado->id])}}">
                                <i class="fa fa-arrow-circle-up"></i>
                            </a>
                        @endif
                    </td>
                    <td>
                        @if (!$loop->last)
                            <a href="{{route('estado.down',['estado' => $estado->id])}}">
                                <i class="fa fa-arrow-circle-down"></i>
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

app/resources/views/estado/show.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
	Change Title here!
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

				<div class="box box-success box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Example box</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        Put your content here
                    </div>
                    <!-- /.box-body -->
                </div>
			</div>
		</div>
	</div>
@endsection