app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('login');
});

Route::get('/orden/load', 'OrdenController@load')->name('orden.load');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => '/cliente'], function() {
        Route::get('/', 'ClienteController@index')->name('cliente.index');
        Route::get('/load', 'ClienteController@load')->name('cliente.load');
        Route::get('/crear', 'ClienteController@create')->name('cliente.crear');
        Route::post('/crear', 'ClienteController@store')->name('cliente.store');
        Route::get('/{cliente}', 'ClienteController@view')->name('cliente.view');
        Route::get('/{cliente}/edit', 'ClienteController@edit')->name('cliente.edit');
        Route::post('/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    });

    Route::group(['prefix' => '/json'], function() {
        Route::get('/cliente/buscar/{dni}', 'ClienteController@buscar')->name('cliente.buscar');
        Route::get('/tipo/{tipo}/marcas', 'TipoController@getMarcas')->name('marcas.tipo');
        Route::get('/tipo/{tipo}/marca/{marca}/modelos', 'TipoController@getModelos')->name('tipos.marcas.modelos');
    });

    Route::resource('tipos', 'TipoController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('modelos', 'ModeloController');
    Route::resource('prestadores', 'PrestadorController');

    Route::resource('fotos', 'FotoController');

    Route::get('/estados/{estado}/arriba', 'EstadoController@up')->name('estado.up');
    Route::get('/estados/{estado}/abajo', 'EstadoController@down')->name('estado.down');

    Route::resource('estados', 'EstadoController');

    Route::group(['prefix' => '/orden'], function() {
        Route::get('/', 'OrdenController@index')->name('orden.index');
        //Route::get('/load', 'OrdenController@load')->name('orden.load');
        Route::get('/{orden}', 'OrdenController@show')->name('orden.show');
        Route::get('/crear/cliente/{cliente}', 'OrdenController@create')->name('orden.create');
        Route::post('/crear', 'OrdenController@store')->name('orden.store');
        Route::post('/{orden}/precio', 'OrdenController@precio')->name('orden.precio');
        Route::post('/{orden}/estado', 'OrdenController@estadoUpdate')->name('orden.estadoupdate');
        Route::get('/{orden}/print', 'OrdenController@print')->name('orden.print');
        Route::get('/{orden}/edit', 'OrdenController@edit')->name('orden.edit');
        Route::post('/{orden}/update', 'OrdenController@update')->name('orden.update');

    });

    Route::group(['prefix' => '/usuarios'], function() {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('/crear', 'UserController@create')->name('users.create');
        Route::post('/', 'UserController@store')->name('users.store');
        Route::get('/{user}', 'UserController@show')->name('users.show');
        Route::get('/{user}/editar', 'UserController@edit')->name('users.edit');
        Route::post('/{user}', 'UserController@update')->name('users.update');
        Route::delete('/{user}', 'UserController@destroy')->name('users.destroy');
    });

    Route::get('/acceso/{user}/cambiar', 'UserController@editPassword')->name('users.password.edit');
    Route::post('/acceso/{user}', 'UserController@updatePassword')->name('users.password.update');

    Route::group(['prefix' => '/historial'], function() {
        Route::get('/{orden}/load', 'HistoriaController@load')->name('historia.load');
    });




//    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/app/Modelo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Modelo extends Model
{
    protected $guarded = ['id'];
    public $appends = ['nombrecompleto'];

    public function marca()
    {
        return $this->hasOne(Marca::class,'id', 'marca_id')->with('tipo');
    }

    public function getNombrecompletoAttribute()
    {
    	return $this->marca->nombre . " - " . $this->nombre;
    }

}

app/app/Http/Controllers/ModeloController.php
<?php

namespace App\Http\Controllers;

use App\Modelo;
use Illuminate\Http\Request;
use App\Marca;
use App\Tipo;
use App\Http\Requests\ModeloPostRequest;

class ModeloController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("modelo.index", ["modelos" => Modelo::all()->sortBy('nombre')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'tipos' => Tipo::all()->sortBy('nombre'),
            'marcas' => Marca::all()->sortBy('nombre'),
        ];
        return view("modelo.create", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ModeloPostRequest $request)
    {
        $modelo = Modelo::create($request->only('nombre', 'marca_id'));

        return redirect(route('modelos.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Modelo '.$modelo->nombre.' creado exitosamente.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Modelo  $modelo
     * @return \Illuminate\Http\Response
     */
    public function show(Modelo $modelo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Modelo  $modelo
     * @return \Illuminate\Http\Response
     */
    public function edit(Modelo $modelo)
    {
        $data = [
            'modelo' => $modelo,
            'marcas' => Marca::all()->sortBy('nombre'),
        ];
        return view("modelo.edit",$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Modelo  $modelo
     * @return \Illuminate\Http\Response
     */
    public function update(ModeloPostRequest $request, Modelo $modelo)
    {
        $modelo->update($request->only('nombre', 'marca_id'));

        return redirect(route('modelos.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Modelo '.$modelo->nombre.' actualizado exitosamente.'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Modelo  $modelo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Modelo $modelo)
    {
        //
    }
}

app/resources/views/modelo/create.blade.php
@extends('layout', [
  'title' => 'Modelo',
  'content_title' => 'Modelo',
  'content_sub_title' => 'Nuevo'
])

@section('content')

<div class="row">
  <div class="col-md-8">
    <div class="box box-primary">
        <form class="form-horizontal" action="{{ route('modelos.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="box-header">Nuevo Modelo</div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Tipo</label>
                        <div class="col-sm-10">
                            <select name="tipo_id" id="tipo_id" class="form-control">
                                <option value="0" disabled selected="selected">Seleccione Tipo...</option>
                                @foreach ($tipos as $tipo)
                                    <option value="{{$tipo->id}}">{{$tipo->nombre}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Marca</label>
                        <div class="col-sm-10">
                            <select name="marca_id" id="marca_id" class="form-control">
                                <option value="0" disabled selected="selected">Seleccione Marca...</option>

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" name="nombre" id="nombre" class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Crear</button>
            </div>
        </form>
    </div>
  </div>
</div>
@endsection

@push('body-scripts')
<script type="text/javascript">
  $(document).ready(() => {
    $("#tipo_id").select2({
            placeholder: 'Seleccione un tipo...',
      });

    $("#tipo_id").on('select2:select', function (e) {
        axios.get(laroute.route('marcas.tipo', { tipo: e.params.data.id }))
        .then((resp) => {

            $("#marca_id").children().remove();

            var listitems = "<option value='0' disabled selected='selected'>Seleccione Marca...</option>";
            $.each(resp.data, function(i, value){
                listitems += "<option value='"+value.id+"'>"+value.nombre+"</option>";
            });
            $('#cursos').select2("destroy");
            $("#marca_id").append(listitems);
            $("#marca_id").select2();

        });

      });
  });
</script>
@endpush

app/resources/views/modelo/edit.blade.php
@extends('layout', [
  'title' => 'Modelo',
  'content_title' => 'Modelo',
  'content_sub_title' => 'Edicion'
])

@section('content')

<div class="row">
  <div class="col-md-8">
    <div class="box box-primary">
        <form class="form-horizontal" action="{{ route('modelos.update',['modelo' => $modelo->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="box-header">Edicion de Modelo</div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Marca</label>
                        <div class="col-sm-10">
                            <select name="marca_id" id="marca_id" class="form-control">
                                <option value="0" disabled selected="selected">Seleccione Marca...</option>
                                @foreach ($marcas as $marca)
                                    @if ($marca->id == $modelo->marca_id)
                                        <option value="{{$marca->id}}" selected="selected">{{$marca->nombre}}</option>
                                    @else
                                        <option value="{{$marca->id}}">{{$marca->nombre}}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" style="width:100px">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" name="nombre" id="nombre" class="form-control" value="{{$modelo->nombre}}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Actualizar</button>
            </div>
        </form>
    </div>
  </div>
</div>
@endsection

app/resources/views/modelo/index.blade.php
@extends('layout', [
  'title' => 'Modelos',
  'content_title' => 'Modelos',
  'content_sub_title' => 'Listado'
])

@section('content')

  <div class="row">
    <div class="col-xs-2 col-xs-offset-10">
      <a class="btn btn-block btn-primary" href="{{ route('modelos.create') }}">Crear Nuevo</a>
    </div>
  </div>
  <br>

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <table id="clientes" class="table table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th>Marca</th>
              <th>Nombre</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($modelos as $modelo)
                <tr>
                    <td>{{ $modelo->marca->nombre }}</td>
                    <td>{{ $modelo->nombre }}</td>
                    <td>
                        <a href="{{route('modelos.edit',['tipo' => $modelo->id])}}"><i class='fa fa-edit'></i></a> 
                        <a href="{{route('modelos.destroy',['tipo' => $modelo->id])}}"><i class="fa fa-remove"></i></a>
                    </td> 
                </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection