app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('login');
});

Route::get('/orden/load', 'OrdenController@load')->name('orden.load');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => '/cliente'], function() {
        Route::get('/', 'ClienteController@index')->name('cliente.index');
        Route::get('/load', 'ClienteController@load')->name('cliente.load');
        Route::get('/crear', 'ClienteController@create')->name('cliente.crear');
        Route::post('/crear', 'ClienteController@store')->name('cliente.store');
        Route::get('/{cliente}', 'ClienteController@view')->name('cliente.view');
        Route::get('/{cliente}/edit', 'ClienteController@edit')->name('cliente.edit');
        Route::post('/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    });

    Route::group(['prefix' => '/json'], function() {
        Route::get('/cliente/buscar/{dni}', 'ClienteController@buscar')->name('cliente.buscar');
        Route::get('/tipo/{tipo}/marcas', 'TipoController@getMarcas')->name('marcas.tipo');
        Route::get('/tipo/{tipo}/marca/{marca}/modelos', 'TipoController@getModelos')->name('tipos.marcas.modelos');
    });

    Route::resource('tipos', 'TipoController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('modelos', 'ModeloController');
    Route::resource('prestadores', 'PrestadorController');

    Route::resource('fotos', 'FotoController');

    Route::get('/estados/{estado}/arriba', 'EstadoController@up')->name('estado.up');
    Route::get('/estados/{estado}/abajo', 'EstadoController@down')->name('estado.down');

    Route::resource('estados', 'EstadoController');

    Route::group(['prefix' => '/orden'], function() {
        Route::get('/', 'OrdenController@index')->name('orden.index');
        //Route::get('/load', 'OrdenController@load')->name('orden.load');
        Route::get('/{orden}', 'OrdenController@show')->name('orden.show');
        Route::get('/crear/cliente/{cliente}', 'OrdenController@create')->name('orden.create');
        Route::post('/crear', 'OrdenController@store')->name('orden.store');
        Route::post('/{orden}/precio', 'OrdenController@precio')->name('orden.precio');
        Route::post('/{orden}/estado', 'OrdenController@estadoUpdate')->name('orden.estadoupdate');
        Route::get('/{orden}/print', 'OrdenController@print')->name('orden.print');
        Route::get('/{orden}/edit', 'OrdenController@edit')->name('orden.edit');
        Route::post('/{orden}/update', 'OrdenController@update')->name('orden.update');

    });

    Route::group(['prefix' => '/usuarios'], function() {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('/crear', 'UserController@create')->name('users.create');
        Route::post('/', 'UserController@store')->name('users.store');
        Route::get('/{user}', 'UserController@show')->name('users.show');
        Route::get('/{user}/editar', 'UserController@edit')->name('users.edit');
        Route::post('/{user}', 'UserController@update')->name('users.update');
        Route::delete('/{user}', 'UserController@destroy')->name('users.destroy');
    });

    Route::get('/acceso/{user}/cambiar', 'UserController@editPassword')->name('users.password.edit');
    Route::post('/acceso/{user}', 'UserController@updatePassword')->name('users.password.update');

    Route::group(['prefix' => '/historial'], function() {
        Route::get('/{orden}/load', 'HistoriaController@load')->name('historia.load');
    });




//    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/app/Orden.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable;
use App\Historia;


class Orden extends Model implements Auditable
{
    use AuditableTrait;

	protected $table = 'ordenes';
    protected $guarded = ['id'];
    protected $appendd = ['clienteNombre'];

    public function clienteRel()
    {
        return $this->hasOne(Cliente::class,'id','cliente_id');
    }

    public function modeloRel()
    {
    	return $this->hasOne(Modelo::class,'id','modelo_id')->with('marca');
    }

    public function garantia()
    {
        return $this->hasOne(Garantia::class, 'id', 'garantia_id')->with('aseguradora');
    }

    public function getClienteNombreAttribute()
    {
    	return $this->clienteRel->nombrecompleto;
    }

    public function estadoRel()
    {
        return $this->hasOne(Estado::class,'id','estado_id');
    }

    public function historias()
    {
        return $this->hasMany(Historia::class);
    }

    public function fotos()
    {
        return $this->hasMany(Fotos::class);
    }
}

app/app/Http/Controllers/OrdenController.php
<?php

namespace App\Http\Controllers;

use App\Orden;
use Illuminate\Http\Request;
use App\Cliente;
use App\Tipo;
use App\Marca;
use App\Http\Requests\OrdenPostRequest;
use Illuminate\Support\Facades\DB;
use App\Garantia;
use App\Estado;
use App\Historia;
use Auth;
use App\Exports\OrdenExport;
use PDF;
use App\Prestador;
use DataTables;

class OrdenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('orden.index');
    }

    public function load()
    {
        $datatables = datatables()->of(Orden::query()->with(['clienteRel','modeloRel','estadoRel'])->orderBy('id', 'desc'));

        $datatables->addColumn('cliente', function($row){
                    return $row->clienteRel->nombrecompleto;
                });

        return $datatables->make(true);

        /*
                ->addColumn('clientenombre', function($row){
                    return $row->clienteRel->nombrecompleto;
                })
                )
                ->toJson();

        /*$model = Orden::with(['clienteRel','modeloRel','estado']);
        return DataTables::eloquent($model)
                ->addColumn('clienteRel', function (Orden $orden) {
                    return $orden->clienteRel->map(function($clienteRel) {
                        return str_limit($clienteRel->apellido, 30, '...');
                    })->implode('<br>');
                })
                ->toJson();*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Cliente $cliente)
    {
        $data = [
            "cliente"   => $cliente,
            'tipos' => Tipo::all()->sortBy('nombre'),
            'marcas' => Marca::all()->sortBy('nombre'),
            'prestadores'   => Prestador::all()->sortBy('nombre'),
        ];
        return view("orden.create", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrdenPostRequest $request)
    {
        try {
            DB::beginTransaction();
                $garantia = Garantia::create([
                    'tipo'  => $request->input('garantia'),
                    'fecha'  => $request->input('fecha'),
                    'lugar'  => $request->input('lugar'),
                    'norden'  => $request->input('norden'),
                    'prestador_id'  => $request->input('aseguradora'),
                ]);

                if ($request->input('diagnostico') != "" and $request->input('precio') != "" )
                {
                    $estado_id = 5;
                }else{
                    $estado_id = Estado::all()->sortBy('orden')->first()->id;
                }

                $orden = Orden::create([
                    'cliente_id'    => $request->input('cliente_id'),
                    'modelo_id'     => $request->input('modelo_id'),
                    'color'         => $request->input('color'),
                    'esn'           => $request->input('esn'),
                    'falla'         => $request->input('falla'),
                    'accesorios'    => $request->input('accesorios'),
                    'prestador'     => $request->input('prestador'),
                    'clave'         => $request->input('clave'),
                    'precio'        => $request->input('precio'),
                    'diagnostico'   => $request->input('diagnostico'),
                    'estado'        => $request->input('estado'),
                    'garantia_id'   => $garantia->id,
                    'estado_id'     => $estado_id,
                ]);

                $historia = Historia::create([
                    'accion'    => 'Nuevo',
                    'orden_id'  => $orden->id,
                    'user_id'   => Auth::user()->id,
                    'mensaje'   => 'Creacion de nueva orden',
                ]);

                if ($request->input('diagnostico') != "" and $request->input('precio') != "" ) {
                    $historia = Historia::create([
                        'accion'    => 'Presupuesto Aprobado',
                        'orden_id'  => $orden->id,
                        'user_id'   => Auth::user()->id,
                        'mensaje'   => 'Orden aprobada por el cliente en el local',
                    ]);
                }

                if ($request->input('otro') != "") {
                    $historia = Historia::create([
                        'accion'    => 'Nuevo',
                        'orden_id'  => $orden->id,
                        'user_id'   => Auth::user()->id,
                        'mensaje'   => 'Equipo no registrado: ' . $request->input('otro'),
                    ]);
                }

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
        }

        return redirect(route('orden.show', ['orden'=>$orden->id]))->with('flash_message', [
            'type' => 'success',
            'message' => 'Orden '.$orden->id.' creada exitosamente.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function show(Orden $orden)
    {
        
        return view('orden.show', ['orden'=>$orden, 'estados' => Estado::all()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function edit(Orden $orden)
    {
        return view('orden.edit', ['orden'=>$orden]);
    }

    public function update(Request $request, Orden $orden)
    {

        $orden->esn = $request->input('esn');
        $orden->color = $request->input('color');
        $orden->falla = $request->input('falla');
        $orden->accesorios = $request->input('accesorios');
        $orden->save();
        return redirect(route('orden.show', ['orden'=>$orden->id]))->with('flash_message', [
            'type' => 'success',
            'message' => 'Orden '.$orden->id.' actualizada exitosamente.'
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function precio(Request $request, Orden $orden)
    {
        $orden->update(['precio' =>$request->input('precio')]);

        $historia = Historia::create([
            'accion'    => 'Precio',
            'orden_id'  => $orden->id,
            'user_id'   => Auth::user()->id,
            'mensaje'   => 'Nuevo precio de $'.$request->input('precio'),
        ]);

        return redirect(route('orden.show',['orden'=>$orden->id]))->with('flash_message', [
            'type' => 'success',
            'message' => 'Precio actualizado exitosamente.'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function estadoUpdate(Request $request, Orden $orden)
    {
        if ($orden->estado_id < 8) {
            if ($request->input('estado') == 3) {
                $orden->update([
                    'estado_id'     =>$request->input('estado'),
                    'precio'        =>$request->input('precio'),
                    'diagnostico'   => $request->input('diagnostico'),
                ]);

                $historia = Historia::create([
                    'accion'    => 'Precio',
                    'orden_id'  => $orden->id,
                    'user_id'   => Auth::user()->id,
                    'mensaje'   => 'Nuevo precio de $'.$request->input('precio'),
                ]);
            }else{
                $orden->update(['estado_id' => $request->input('estado')]);
            }

            $historia = Historia::create([
                'accion'    => 'Estado',
                'orden_id'  => $orden->id,
                'user_id'   => Auth::user()->id,
                'mensaje'   => 'Cambio de estado a '. $orden->estadoRel->nombre,
            ]);
            return redirect(route('orden.show',['orden'=>$orden->id]))->with('flash_message', [
                'type' => 'success',
                'message' => 'Cambio de estado a ' . $orden->estadoRel->nombre . " exitoso."
            ]);
        }else{
            return redirect(route('orden.show',['orden'=>$orden->id]))->with('flash_message', [
                'type' => 'info',
                'message' => 'No es posible cambiar el estado de la orden, porque ya ha sido cerrada'
        ]);
        }
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function destroy(Orden $orden)
    {
        //
    }

    /**
     * Print the specified resource from storage.
     *
     * @param  \App\Orden  $orden
     * @return \Illuminate\Http\Response
     */
    public function print(Orden $orden)
    {
        $data['orden'] = $orden;
        $data['cliente'] = $orden->clienteRel;
        $data['equipo'] = $orden->modeloRel;
        $data['garantia'] = $orden->garantia;
        $pdf = PDF::loadView('orden.ticket', $data);
        return $pdf->stream();
    }
}

app/resources/views/orden/edit.blade.php
@extends('layout', [
  'title' => 'Orden',
  'content_title' => 'Orden',
  'content_sub_title' => $orden->id,
])

@section('content')

<div class="row form-horizontal">
    <div class="col-md-8">
        <form action="{{route('orden.update',['orden'=>$orden->id])}}" method="POST">
            @csrf
            <div class="box box-primary box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">Modificación de Orden</h3></div>
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Equipo</label>
                            <div class="col-sm-9">
                                <input type="text" name="" value="{{ $orden->modeloRel->nombrecompleto }}" class="form-control" disabled>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">IMEI/Serial</label>
                            <div class="col-sm-5">
                                <input type="text" name="esn" id="esn" value="{{ $orden->esn }}" class="form-control">
                            </div>
                            <label class="col-sm-1 control-label">Color</label>
                            <div class="col-sm-3">
                                <input type="text" name="color" id="color" value="{{ $orden->color }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Falla</label>
                            <div class="col-sm-9">
                                <textarea rows="2" class="form-control" name="falla" id="falla">{{ $orden->falla }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Accesorios</label>
                            <div class="col-sm-9">
                                <textarea rows="2" class="form-control" id="accesorios" name="accesorios">{{ $orden->accesorios }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-info pull-right" >Actualizar</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

app/resources/views/orden/index.blade.php
@extends('layout', [
  'title' => 'Ordenes',
  'content_title' => 'Ordenes',
  'content_sub_title' => 'Listado'
])

@section('content')

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <table id="ordenes" class="table table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th>Orden</th>
              <th>Estado</th>
              <th>Cliente</th>
              <!-- <th>Apellido</th> -->
              <th>Modelo</th>
              <th>Color</th>
              <th>IMEI</th>
              <th>Falla</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

<select name="estado" id="estado" class="form-control"></select>

@push('body-scripts')
<script type="text/javascript">
  function addHeaderInputsToHeader(datatable) {
    let row = '<tr>';
    datatable.columns().every(function (index) {
        // let column = datatable.column($(this).parent().index() + ':visible');
        // let idx = column.index();
        let settings = datatable.settings()[0].aoColumns[index];
        row += '<th>';
        if (settings.bSearchable) {
          if (settings.sTitle == "Estado") {
            row += '<select class="form-control" id="estado"><option value="" selected="selected">Todos</option> <option value="1">Ingreso</option> <option value="2">Diagnostico</option> <option value="4">Presupuesto</option> <option value="5">Presupuesto Aprobado</option> <option value="7">Pendiente por Material</option> <option value="8">Terminado Reparado</option> <option value="9">Terminado No Reparado</option> <option value="10">Entregado Reparado</option> <option value="11">Entregado No Reparado</option></select>'
          }else{
            if (settings.sTitle == "Orden" || settings.sTitle == "Color") {
              row += '<input type="text" placeholder="' + settings.sTitle + '" class="form-control" style="width:110px;" />'
            }else{
              row += '<input type="text" placeholder="' + settings.sTitle + '" class="form-control" />'
            }
          }
        }
        row += '</th>';
    });
    row += '</tr>';

    let $header = $(datatable.table().header());
    $header.prepend(row);
    $header.on('keyup change', 'input.form-control, select.form-control', _.debounce(function () {
        let input = this;
        datatable.column($(input).parent().index() + ':visible')
            .search(input.value)
            .draw();
    }, 500));
  }

  $(document).ready(() => {
    let datatable = $('#ordenes').DataTable({
      'processing': true,
      'serverSide': true,
      'ajax': {
        'url': '{{ route('orden.load') }}',
        'type': 'GET'
      },
      'columns': [
        {data: 'id', searchable: true},
        {data: 'estado_id', searchable: true},
        {data: 'cliente_rel.nombrecompleto', searchable: true},
        //{data: 'cliente', searchable: true},
        {data: 'modelo_rel.nombrecompleto', searchable: true},
        {data: 'color', searchable: true},
        {data: 'esn', searchable: true},
        {data: 'falla', searchable: true},
      ],
      'columnDefs': [
        {
          render: (data, type, row) => {
              return '<a href="' + laroute.route('orden.show', { orden: row.id }) + '">' + row.id + '</a>';
          },
          'targets': [0]
        },
        {
          render: (data, type, row) => {
              return row.estado_rel.nombre;
          },
          'targets': [1]
        },
      ]
    });
    addHeaderInputsToHeader(datatable);
  });
</script>
@endpush

app/resources/views/orden/show.blade.php
@extends('layout', [
  'title' => 'Orden',
  'content_title' => 'Orden',
  'content_sub_title' => $orden->id,
])

@section('content')

<div class="row form-horizontal">
    <div class="col-md-8">
        <cliente-ficha
        :cliente="{{ $orden->clienteRel }}"
        ></cliente-ficha>

        <div class="box box-primary box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Detalle de Orden</h3></div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Equipo</label>
                        <div class="col-sm-9">
                            <input type="text" name="" value="{{ $orden->modeloRel->nombrecompleto }}" class="form-control" disabled>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">IMEI/Serial</label>
                        <div class="col-sm-5">
                            <input type="text" name="esn" id="esn" value="{{ $orden->esn }}" class="form-control" disabled>
                        </div>
                        <label class="col-sm-1 control-label">Color</label>
                        <div class="col-sm-3">
                            <input type="text" name="color" id="color" value="{{ $orden->color }}" class="form-control" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Falla</label>
                        <div class="col-sm-9">
                            <textarea rows="2" class="form-control" name="falla" id="falla" disabled>{{ $orden->falla }}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Accesorios</label>
                        <div class="col-sm-9">
                            <textarea rows="2" class="form-control" id="accesorios" name="accesorios" readonly="readonly">{{ $orden->accesorios }}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a class="btn btn-info pull-right" href="{{route('orden.edit',['orden'=>$orden->id])}}" >Editar</a>
            </div>
        </div>

        <div class="box box-primary box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Historial</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                @include('orden.partials.historial')
            </div>
        </div>
    </div>
    <div class="col-md-4">

        <div class="box box-primary box-solid">
            <div class="box-header">Imprimir</div>
            <div class="box-body">
                <a href="{{route('orden.print',['orden'=>$orden->id])}}" target="_BLANK">
                    <img src="/img/pdf-128.png" width="64px">
                </a>
            </div>
        </div>

        <div class="box box-primary box-solid">
            <form action="{{ route('fotos.store') }}" method="POST" enctype="multipart/form-data">
            <div class="box-header">Foto</div>
            <div class="box-body">
                {{ csrf_field() }}
                <input type="hidden" name="orden" value="{{ $orden->id }}">
                <input type="file" name="foto">
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Guardar</button>
            </div>
            </form>
        </div>

        <div class="box box-primary box-solid">
            <div class="box-header">Información Extra</div>
            <div class="box-body">
                <p><b>Prestador: </b>{{ $orden->prestador }}</p>
                <p><b>Clave: </b>{{ $orden->clave }}</p>
                <p><b>Estado: </b>{{ $orden->estado }}</p>
            </div>
        </div>

        <form action="{{route('orden.estadoupdate',['orden'=> $orden->id])}}" method="POST">
            <div class="box box-primary box-solid">
                {{ csrf_field() }}
                <div class="box-header">Estado Actual <small class="label label-warning"></i>{{ $orden->estadoRel->nombre }}</small></div>
                <div class="box-body">

                    <select name="estado" id="estado" class="form-control">
                        <option value="0" disabled="disabled" selected="selected">Seleccione estado nuevo</option>
                        @foreach ($estados as $estado)
                            @if ($orden->estado_id == $estado->id)
                                <option value="{{ $estado->id }}" selected="selected">{{ $estado->nombre }}</option>
                            @else
                                <option value="{{ $estado->id }}">{{ $estado->nombre }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="box-body precio-frame">
                    <div class="form-group {{$errors->has('diagnostico') ? 'has-error' : ''}}">
                        <label class="col-sm-3 control-label">Diagnostico</label>
                        <div class="col-sm-8">
                            <textarea rows="3" name="diagnostico" id="diagnostico" class="form-control" readonly="true">{{ $orden->diagnostico }}</textarea>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        <input type="text" name="precio" id="precio" class="form-control" value="{{ $orden->precio }}" readonly="true">
                        <span class="input-group-addon">.00</span>
                    </div>
                </div>
                <div class="box-footer">
                    @if ($orden->estado_id < 8)
                        <button type="submit" class="btn btn-info pull-right">Guardar</button>
                    @endif
                </div>
            </div>
        </form>

        <div class="box box-primary box-solid">
            <div class="box-header">{{ $orden->garantia->nombre }}</div>
            @if ($orden->garantia->tipo > 1)
            <div class="box-body">
                <p><b>Lugar de compra: </b>{{ $orden->garantia->lugar }}</p>
                @if ($orden->garantia->aseguradora)
                    <p><b>Prestador: </b>{{ $orden->garantia->aseguradora->nombre }}</p>
                @endif
                <p><b>Fecha de compra: </b>{{ $orden->garantia->fecha }}</p>
            </div>
            @endif
        </div>

        <!-- <div class="box box-primary">
            <div class="box-header">Fotos</div>
            <div class="box-body">
                FOTOS
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Crear</button>
            </div>
        </div> -->

    </div>
</div>
@endsection


@push('body-scripts')
<script type="text/javascript">
    $(document).ready(() => {

        $( "#estado" ).change(function() {
            if ($("#estado").val() == 3) {
                $("#precio").attr('readonly', false);
                $("#diagnostico").attr('readonly', false);
            }else{
                $("#precio").attr('readonly', true);
                $("#diagnostico").attr('readonly', true);
            }
        });

    });
</script>
@endpush

app/resources/views/orden/view.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
	Change Title here!
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

				<div class="box box-success box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Example box</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        Put your content here
                    </div>
                    <!-- /.box-body -->
                </div>
			</div>
		</div>
	</div>
@endsection