app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('login');
});

Route::get('/orden/load', 'OrdenController@load')->name('orden.load');

Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => '/cliente'], function() {
        Route::get('/', 'ClienteController@index')->name('cliente.index');
        Route::get('/load', 'ClienteController@load')->name('cliente.load');
        Route::get('/crear', 'ClienteController@create')->name('cliente.crear');
        Route::post('/crear', 'ClienteController@store')->name('cliente.store');
        Route::get('/{cliente}', 'ClienteController@view')->name('cliente.view');
        Route::get('/{cliente}/edit', 'ClienteController@edit')->name('cliente.edit');
        Route::post('/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    });

    Route::group(['prefix' => '/json'], function() {
        Route::get('/cliente/buscar/{dni}', 'ClienteController@buscar')->name('cliente.buscar');
        Route::get('/tipo/{tipo}/marcas', 'TipoController@getMarcas')->name('marcas.tipo');
        Route::get('/tipo/{tipo}/marca/{marca}/modelos', 'TipoController@getModelos')->name('tipos.marcas.modelos');
    });

    Route::resource('tipos', 'TipoController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('modelos', 'ModeloController');
    Route::resource('prestadores', 'PrestadorController');

    Route::resource('fotos', 'FotoController');

    Route::get('/estados/{estado}/arriba', 'EstadoController@up')->name('estado.up');
    Route::get('/estados/{estado}/abajo', 'EstadoController@down')->name('estado.down');

    Route::resource('estados', 'EstadoController');

    Route::group(['prefix' => '/orden'], function() {
        Route::get('/', 'OrdenController@index')->name('orden.index');
        //Route::get('/load', 'OrdenController@load')->name('orden.load');
        Route::get('/{orden}', 'OrdenController@show')->name('orden.show');
        Route::get('/crear/cliente/{cliente}', 'OrdenController@create')->name('orden.create');
        Route::post('/crear', 'OrdenController@store')->name('orden.store');
        Route::post('/{orden}/precio', 'OrdenController@precio')->name('orden.precio');
        Route::post('/{orden}/estado', 'OrdenController@estadoUpdate')->name('orden.estadoupdate');
        Route::get('/{orden}/print', 'OrdenController@print')->name('orden.print');
        Route::get('/{orden}/edit', 'OrdenController@edit')->name('orden.edit');
        Route::post('/{orden}/update', 'OrdenController@update')->name('orden.update');

    });

    Route::group(['prefix' => '/usuarios'], function() {
        Route::get('/', 'UserController@index')->name('users.index');
        Route::get('/crear', 'UserController@create')->name('users.create');
        Route::post('/', 'UserController@store')->name('users.store');
        Route::get('/{user}', 'UserController@show')->name('users.show');
        Route::get('/{user}/editar', 'UserController@edit')->name('users.edit');
        Route::post('/{user}', 'UserController@update')->name('users.update');
        Route::delete('/{user}', 'UserController@destroy')->name('users.destroy');
    });

    Route::get('/acceso/{user}/cambiar', 'UserController@editPassword')->name('users.password.edit');
    Route::post('/acceso/{user}', 'UserController@updatePassword')->name('users.password.update');

    Route::group(['prefix' => '/historial'], function() {
        Route::get('/{orden}/load', 'HistoriaController@load')->name('historia.load');
    });




//    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/app/Tipo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tipo extends Model
{
    protected $guarded = ['id'];

    public function marcas()
    {
        return $this->hasMany(Marca::class)->with('modelos');
    }
}

app/app/Http/Controllers/TipoController.php
<?php

namespace App\Http\Controllers;

use App\Tipo;
use Illuminate\Http\Request;
use App\Http\Requests\TipoPostRequest;
use App\Marca;
use App\Modelo;

class TipoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("tipo.index", ['tipos' => Tipo::all()->sortBy('nombre')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("tipo.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TipoPostRequest $request)
    {
        $tipo = Tipo::create($request->only('nombre'));

        return redirect(route('tipos.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Tipo '.$tipo->nombre.' creado exitosamente.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tipo  $tipo
     * @return \Illuminate\Http\Response
     */
    public function show(Tipo $tipo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tipo  $tipo
     * @return \Illuminate\Http\Response
     */
    public function edit(Tipo $tipo)
    {
        return view("tipo.edit", ['tipo' => $tipo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tipo  $tipo
     * @return \Illuminate\Http\Response
     */
    public function update(TipoPostRequest $request, Tipo $tipo)
    {
        $tipo->update($request->only('nombre'));

        return redirect(route('tipos.index'))->with('flash_message', [
            'type' => 'success',
            'message' => 'Tipo '.$tipo->nombre.' actualizado exitosamente.'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tipo  $tipo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tipo $tipo)
    {
        //
    }

    public function getMarcas(Tipo $tipo)
    {
        return response()->json(Marca::all()->where('tipo_id', $tipo->id));
    }

    public function getModelos(Tipo $tipo, Marca $marca)
    {
        return response()->json($tipo->marcas->where('id',$marca->id)->first()->modelos);
    }
}

app/resources/views/tipo/create.blade.php
@extends('layout', [
  'title' => 'Tipos',
  'content_title' => 'Tipo',
  'content_sub_title' => 'Nuevo'
])

@section('content')

<div class="row">
  <div class="col-xs-6">
    <div class="box box-primary">
        <form class="form-horizontal" action="{{ route('tipos.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="box-header">Nuevo Tipo</div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-sm-9">
                        <label class="control-label" style="width:100px">Nombre</label>
                        <input type="text" name="nombre" id="nombre">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Crear</button>
            </div>
        </form>
    </div>
  </div>
</div>
@endsection

app/resources/views/tipo/edit.blade.php
@extends('layout', [
  'title' => 'Tipos',
  'content_title' => 'Tipo',
  'content_sub_title' => 'Edicion'
])

@section('content')

<div class="row">
  <div class="col-xs-6">
    <div class="box box-primary">
        <form class="form-horizontal" action="{{ route('tipos.update',['tipo' => $tipo->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="box-header">Edicio de Tipo</div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-sm-9">
                        <label class="control-label" style="width:100px">Nombre</label>
                        <input type="text" name="nombre" id="nombre" value="{{$tipo->nombre}}">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Actualizar</button>
            </div>
        </form>
    </div>
  </div>
</div>
@endsection

app/resources/views/tipo/index.blade.php
@extends('layout', [
  'title' => 'Tipos',
  'content_title' => 'Tipos',
  'content_sub_title' => 'Listado'
])

@section('content')

  <div class="row">
    <div class="col-xs-2 col-xs-offset-10">
      <a class="btn btn-block btn-primary" href="{{ route('tipos.create') }}">Crear Nuevo</a>
    </div>
  </div>
  <br>

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body">
        <table id="clientes" class="table table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($tipos as $tipo)
                <tr>
                    <td>{{ $tipo->nombre }}</td>
                    <td>
                        <a href="{{route('tipos.edit',['tipo' => $tipo->id])}}"><i class='fa fa-edit'></i></a> 
                        <a href="{{route('tipos.destroy',['tipo' => $tipo->id])}}"><i class="fa fa-remove"></i></a>
                    </td> 
                </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection